package zshimport

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
)

// Run implements `grsh init`: read the user's zsh startup files, translate
// them, and write ~/.grshrc — or ~/.grshrc.new when one already exists,
// never overwriting user config. Returns a process exit code.
func Run(stdout, stderr io.Writer) int {
	home, err := os.UserHomeDir()
	if err != nil || home == "" {
		fmt.Fprintln(stderr, "grsh init: cannot determine home directory")
		return 2
	}

	var combined Result
	var body string
	found := false
	// zsh's own load order for interactive shells.
	for _, name := range []string{".zshenv", ".zprofile", ".zshrc"} {
		b, err := os.ReadFile(filepath.Join(home, name))
		if err != nil {
			continue
		}
		found = true
		r := Translate(string(b))
		body += fmt.Sprintf("# ---- translated from ~/%s ----\n%s\n", name, r.Output)
		combined.Active += r.Active
		combined.Skipped += r.Skipped
		combined.Todos += r.Todos
	}
	if !found {
		fmt.Fprintln(stderr, "grsh init: no ~/.zshrc (or .zshenv/.zprofile) found")
		return 1
	}

	out := "# Generated by `grsh init` — translated from your zsh startup files.\n" +
		"# Active lines below behave the same in grsh. Lines marked [zsh ...]\n" +
		"# had no safe translation and are preserved as comments; TODO lines\n" +
		"# point at things worth porting by hand (grsh mixes shell and Go, so\n" +
		"# zsh functions usually become Go funcs).\n\n" + body

	target := filepath.Join(home, ".grshrc")
	if _, err := os.Stat(target); err == nil {
		target = filepath.Join(home, ".grshrc.new")
		fmt.Fprintf(stdout, "~/.grshrc already exists; writing ~/.grshrc.new instead\n")
	}
	if err := os.WriteFile(target, []byte(out), 0644); err != nil {
		fmt.Fprintf(stderr, "grsh init: %v\n", err)
		return 2
	}
	fmt.Fprintf(stdout, "wrote %s: %d active line(s), %d preserved as comments, %d TODO(s)\n",
		target, combined.Active, combined.Skipped, combined.Todos)
	return 0
}
